"""
LLM Coach interface and State-to-Text conversion for Google Research Football.

This module contains:
- GRFNarrator: Translates raw Simple115 observations into natural language descriptions.
- COACH_SYSTEM_PROMPT / COACH_USER_PROMPT_TEMPLATE: Prompts used to query the LLM Coach.
- DeepSeekCoach / GroqCoach: Async LLM clients with caching for action mask generation.
"""

import math
import numpy as np
import threading
import collections
import json
import time
from datetime import datetime, timedelta


GAME_MODE_NAMES = ["Normal", "Kick-Off", "Goal Kick", "Free Kick", "Corner", "Throw-In", "Penalty"]


class GRFNarrator:
    """
    Translates raw Google Research Football (GRF) observations into descriptive
    natural language text, serving as the input state for the LLM Coach.

    Mathematical Logic for Coordinate-to-Text Translation:
    ------------------------------------------------------
    The GRF environment operates on a normalized 2D pitch coordinate system:
      - X-axis (length): Ranges from -1.0 (left goal) to +1.0 (right goal).
      - Y-axis (width): Ranges from -0.42 (top sideline) to +0.42 (bottom sideline).
      - Z-axis (height): Ranges from 0.0 to 1.0.

    Attacking Direction:
    By default, the active agent's team (Left Team) attacks the right goal, located at x = 1.0.
    The opponent (Right Team) attacks the left goal at x = -1.0.

    Spatial Zones (X-axis):
    We split the pitch into three zones to give the LLM high-level spatial context:
      - Defensive Third: x < -0.33
      - Midfield: -0.33 <= x <= 0.33
      - Attacking Third: x > 0.33

    Distance Calculations:
    Euclidean distance is calculated as sqrt((x2 - x1)^2 + (y2 - y1)^2).
    In GRF scale, a distance of 0.1 is roughly 5 meters. This allows us to quantify
    how "open" a teammate is or how close the ball is to the goal.
    """

    def __init__(self):
        pass

    def get_pitch_zone(self, x: float) -> str:
        """Returns the pitch zone based on the x-coordinate."""
        if x < -0.33:
            return "Defensive third"
        elif x <= 0.33:
            return "Midfield"
        else:
            return "Attacking third"

    def translate(self, features: dict) -> str:
        """
        Translates a parsed features dictionary into a concise narrative string.
        Coordinates are rounded to 1 decimal place to improve cache hit rates.

        Args:
            features (dict): Dictionary generated by core.wrappers.observation_to_features()

        Returns:
            str: Natural language description of the game state.
        """
        ball_x = features.get("ball_x", 0.0)
        ball_y = features.get("ball_y", 0.0)
        active_idx = features.get("active_player_idx", -1)
        owner_id = features.get("ball_owned_team", -1)
        game_mode_idx = features.get("game_mode", 0)

        ball_zone = self.get_pitch_zone(ball_x)

        if owner_id == 0:
            owner_str = "Our team has the ball"
        elif owner_id == 1:
            owner_str = "The opposing team has the ball"
        else:
            owner_str = "The ball is loose"

        game_mode_str = GAME_MODE_NAMES[game_mode_idx] if 0 <= game_mode_idx < len(GAME_MODE_NAMES) else "Normal"

        narrative = [
            "Game State Summary:",
            f"- Game Mode: {game_mode_str}.",
            f"- Ball Position: {ball_zone} (x={ball_x:.1f}, y={ball_y:.1f}).",
            f"- Possession: {owner_str}.",
        ]

        left_xs = features.get("left_team_xs", [])
        left_ys = features.get("left_team_ys", [])

        if active_idx != -1 and active_idx < len(left_xs):
            ax, ay = left_xs[active_idx], left_ys[active_idx]
            active_dist = math.sqrt((ax - ball_x) ** 2 + (ay - ball_y) ** 2)

            # Determine if active player is the ball carrier:
            # heuristic — our team has possession AND active player is the closest
            # left-team player to the ball.
            if owner_id == 0 and left_xs:
                left_dists = [
                    math.sqrt((lx - ball_x) ** 2 + (ly - ball_y) ** 2)
                    for lx, ly in zip(left_xs, left_ys)
                ]
                ball_carrier_idx = int(np.argmin(left_dists))
                ball_status = (
                    " (ball carrier)"
                    if ball_carrier_idx == active_idx
                    else f" ({active_dist:.2f} units from ball, teammate {ball_carrier_idx} has it)"
                )
            else:
                ball_status = f" ({active_dist:.2f} units from ball)"

            narrative.append(
                f"- Active Agent (You): Player {active_idx} in {self.get_pitch_zone(ax)}"
                f" (x={ax:.1f}, y={ay:.1f}){ball_status}."
            )

            # Show 2 closest teammates to ball (excluding active player)
            teammate_dists = sorted(
                [
                    (math.sqrt((lx - ball_x) ** 2 + (ly - ball_y) ** 2), i, lx, ly)
                    for i, (lx, ly) in enumerate(zip(left_xs, left_ys))
                    if i != active_idx
                ]
            )
            for dist, i, lx, ly in teammate_dists[:2]:
                narrative.append(
                    f"  * Teammate {i} in {self.get_pitch_zone(lx)}"
                    f" (x={lx:.1f}, y={ly:.1f}), {dist:.2f} units from ball."
                )

        # Show 2 closest opponents to ball (defenders / keeper)
        right_xs = features.get("right_team_xs", [])
        right_ys = features.get("right_team_ys", [])
        if right_xs:
            opponent_dists = sorted(
                [
                    (math.sqrt((rx - ball_x) ** 2 + (ry - ball_y) ** 2), i, rx, ry)
                    for i, (rx, ry) in enumerate(zip(right_xs, right_ys))
                ]
            )
            for dist, i, rx, ry in opponent_dists[:2]:
                narrative.append(
                    f"  * Opponent {i} in {self.get_pitch_zone(rx)}"
                    f" (x={rx:.1f}, y={ry:.1f}), {dist:.2f} units from ball."
                )

        return "\n".join(narrative)



COACH_SYSTEM_PROMPT = """You are an expert football coach analyzing a match in the Google Research Football environment.

Your task is to:
1. Assign a tactical "Role" to the active agent (e.g., Attacker, Supporter, Defender).
2. Determine which of the 19 possible actions should be FORBIDDEN based on this role and the current state.

Available Actions in GRF (0-18):
0: Idle
1: Left, 2: TopLeft, 3: Top, 4: TopRight
5: Right, 6: BottomRight, 7: Bottom, 8: BottomLeft
9: LongPass, 10: HighPass, 11: ShortPass, 12: Shot
13: Sprint, 14: ReleaseDirection, 15: ReleaseSprint
16: Sliding, 17: Dribble, 18: ReleaseDribble

Rules for Forbidden_Actions:
- NEVER include directional movement actions (1-8). The agent must always be able to move freely.
- Only forbid tactical actions (0, 9-18) that are contextually inappropriate for the role/state.
- Return at most 7 forbidden actions.
- Prioritize the most harmful actions first in the list.
- Examples:
  * Forbid Shot (12) when the active player is not the ball carrier or is in own half.
  * Forbid LongPass/HighPass (9, 10) and Shot (12) when the opposing team has the ball.
  * Forbid Sliding (16) when our team has possession (risks losing the ball).
  * Forbid Dribble (17) when far from goal and a pass is clearly better.
  * In Penalty mode, forbid all passes (9, 10, 11) — shoot only.

Output your response strictly in the following JSON format:
{
    "Role": "<role_name>",
    "Forbidden_Actions": [<list of integer action IDs to mask>]
}
"""

COACH_USER_PROMPT_TEMPLATE = """The current game state is described below:

{narrative}
"""


class DeepSeekCoach:
    """
    Production service for DeepSeek V3.2 API integration.
    Queries the LLM with the game narrative to determine tactical roles and Action Masks.
    Uses asynchronous API calls and caching to prevent blocking the training loop,
    and leverages context caching by splitting the system and user prompts.
    """
    def __init__(self, api_key: str, model: str = "deepseek-chat"):
        try:
            from openai import OpenAI
        except ImportError:
            raise ImportError("Please install the `openai` package to use the DeepSeek API.")
            
        self.narrator = GRFNarrator()
        self.client = OpenAI(
            api_key=api_key, 
            base_url="https://api.deepseek.com"
        )
        self.model = model
        self.total_tokens_used = 0
        self.total_api_calls = 0
        self.total_api_latency = 0.0
        self.latest_api_latency = 0.0
        
        # Async and caching state
        self.advice_cache = collections.OrderedDict()
        self.cache_size = 1000
        self.cache_hits = 0
        self.cache_misses = 0
        self.latest_advice = {
            "Role": "Fallback (Initializing)",
            "Forbidden_Actions": [],
            "_tokens_used_this_call": 0,
            "_total_tokens_used": 0,
            "_cache_hits": 0,
            "_cache_misses": 0,
            "_latest_api_latency": 0.0,
            "_avg_api_latency": 0.0
        }
        self.pending_requests = set()
        self.lock = threading.Lock()

    def _fetch_advice_async(self, narrative: str):
        prompt = COACH_USER_PROMPT_TEMPLATE.format(narrative=narrative)
        try:
            start_time = time.time()
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": COACH_SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                response_format={'type': 'json_object'},
                max_tokens=100,
                temperature=0.0
            )
            elapsed_time = time.time() - start_time
            
            raw_content = response.choices[0].message.content
            advice = json.loads(raw_content)
            
            with self.lock:
                self.total_api_calls += 1
                self.total_api_latency += elapsed_time
                self.latest_api_latency = elapsed_time

                if response.usage:
                    self.total_tokens_used += response.usage.total_tokens
                
                # Basic validation
                if "Role" not in advice:
                     advice["Role"] = "Unknown"
                if "Forbidden_Actions" not in advice:
                     advice["Forbidden_Actions"] = []
                     
                advice["_tokens_used_this_call"] = response.usage.total_tokens if response.usage else 0
                advice["_total_tokens_used"] = self.total_tokens_used
                
                self.advice_cache[narrative] = advice
                if len(self.advice_cache) > self.cache_size:
                    self.advice_cache.popitem(last=False)
                    
                self.latest_advice = advice
                
        except Exception as e:
            print(f"[DeepSeekCoach] API Error: {e}")
        finally:
            with self.lock:
                self.pending_requests.discard(narrative)

    def get_coaching_advice(self, features: dict) -> dict:
        """
        Translates the state into narrative, checks cache, and returns latest advice.
        If cache miss, launches a background thread to fetch new advice via DeepSeek API.
        """
        narrative = self.narrator.translate(features)
        
        with self.lock:
            # Check cache hit
            if narrative in self.advice_cache:
                self.cache_hits += 1
                advice = self.advice_cache[narrative].copy()
                advice["_cache_hits"] = self.cache_hits
                advice["_cache_misses"] = self.cache_misses
                advice["_latest_api_latency"] = self.latest_api_latency
                advice["_avg_api_latency"] = self.total_api_latency / max(1, self.total_api_calls)
                return advice
            
            # Cache miss - start async fetch if not already pending
            self.cache_misses += 1
            if narrative not in self.pending_requests:
                self.pending_requests.add(narrative)
                thread = threading.Thread(target=self._fetch_advice_async, args=(narrative,))
                thread.daemon = True
                thread.start()
            
            # Return latest known advice immediately
            advice = self.latest_advice.copy()
            advice["_cache_hits"] = self.cache_hits
            advice["_cache_misses"] = self.cache_misses
            advice["_latest_api_latency"] = self.latest_api_latency
            advice["_avg_api_latency"] = self.total_api_latency / max(1, self.total_api_calls)
            return advice

# Models ordered by preference. When a model's daily token quota is exhausted,
# the coach automatically falls back to the next model in the list.
# Free-tier daily token limits (TPD) as of 2026-03:
#   llama-3.3-70b-versatile : 100K  (better reasoning, preferred)
#   llama-3.1-8b-instant    : 500K  (highest free quota, fallback)
GROQ_MODEL_PRIORITY = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
]


class GroqCoach:
    """
    Production service for Groq API integration (e.g., Llama 3).
    Queries the LLM with the game narrative to determine tactical roles and Action Masks.
    Uses asynchronous API calls and caching to prevent blocking the training loop,
    and leverages context caching by splitting the system and user prompts.

    Automatically falls back to the next model in GROQ_MODEL_PRIORITY when a model's
    daily free-tier token quota is exhausted (RateLimitError mentioning "day").
    """
    def __init__(self, api_key: str, model: str = GROQ_MODEL_PRIORITY[0]):
        try:
            import groq as _groq
        except ImportError:
            raise ImportError("Please install the `groq` package to use the Groq API.")

        self._groq = _groq
        self.narrator = GRFNarrator()
        self.client = _groq.Groq(api_key=api_key)

        # Priority list: caller's preferred model first, then remaining fallbacks
        self._model_priority = [model] + [m for m in GROQ_MODEL_PRIORITY if m != model]
        self._model_exhausted_until: dict = {}  # model -> datetime when quota resets
        self.model = model  # kept for external inspection / logging
        self.total_tokens_used = 0
        self.total_api_calls = 0
        self.total_api_latency = 0.0
        self.latest_api_latency = 0.0
        
        # Async and caching state
        self.advice_cache = collections.OrderedDict()
        self.cache_size = 1000
        self.cache_hits = 0
        self.cache_misses = 0
        self.latest_advice = {
            "Role": "Fallback (Initializing)",
            "Forbidden_Actions": [],
            "_tokens_used_this_call": 0,
            "_total_tokens_used": 0,
            "_cache_hits": 0,
            "_cache_misses": 0,
            "_latest_api_latency": 0.0,
            "_avg_api_latency": 0.0
        }
        self.pending_requests = set()
        self.lock = threading.Lock()

    def _active_model(self) -> str:
        """Return the first non-exhausted model. Caller must hold self.lock."""
        now = datetime.now()
        for m in self._model_priority:
            if now >= self._model_exhausted_until.get(m, datetime.min):
                return m
        # All models exhausted — return the one whose quota resets soonest
        return min(self._model_priority, key=lambda m: self._model_exhausted_until[m])

    def _fetch_advice_async(self, narrative: str):
        with self.lock:
            model = self._active_model()

        prompt = COACH_USER_PROMPT_TEMPLATE.format(narrative=narrative)
        try:
            start_time = time.time()
            response = self.client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": COACH_SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                response_format={'type': 'json_object'},
                max_tokens=200,
                temperature=0.0
            )
            elapsed_time = time.time() - start_time

            raw_content = response.choices[0].message.content
            advice = json.loads(raw_content)

            with self.lock:
                self.total_api_calls += 1
                self.total_api_latency += elapsed_time
                self.latest_api_latency = elapsed_time
                self.model = model  # reflect active model

                if getattr(response, "usage", None):
                    self.total_tokens_used += response.usage.total_tokens

                # Basic validation
                if "Role" not in advice:
                    advice["Role"] = "Unknown"
                if "Forbidden_Actions" not in advice:
                    advice["Forbidden_Actions"] = []

                advice["_tokens_used_this_call"] = response.usage.total_tokens if getattr(response, "usage", None) else 0
                advice["_total_tokens_used"] = self.total_tokens_used

                self.advice_cache[narrative] = advice
                if len(self.advice_cache) > self.cache_size:
                    self.advice_cache.popitem(last=False)

                self.latest_advice = advice

        except self._groq.RateLimitError as e:
            msg = str(e).lower()
            is_daily = "day" in msg or "per_day" in msg
            with self.lock:
                if is_daily:
                    reset_at = datetime.now() + timedelta(hours=24)
                    self._model_exhausted_until[model] = reset_at
                    next_model = self._active_model()
                    print(f"[GroqCoach] Daily token quota exhausted for '{model}'. "
                          f"Switching to '{next_model}' (resets ~{reset_at.strftime('%H:%M')})")
                else:
                    # Tokens-per-minute limit — transient, don't blacklist the model
                    print(f"[GroqCoach] Rate limit (TPM) for '{model}': {e}")

        except Exception as e:
            print(f"[GroqCoach] API Error: {e}")
        finally:
            with self.lock:
                self.pending_requests.discard(narrative)

    def get_coaching_advice(self, features: dict) -> dict:
        """
        Translates the state into narrative, checks cache, and returns latest advice.
        If cache miss, launches a background thread to fetch new advice via Groq API.
        """
        narrative = self.narrator.translate(features)
        
        with self.lock:
            # Check cache hit
            if narrative in self.advice_cache:
                self.cache_hits += 1
                advice = self.advice_cache[narrative].copy()
                advice["_cache_hits"] = self.cache_hits
                advice["_cache_misses"] = self.cache_misses
                advice["_latest_api_latency"] = self.latest_api_latency
                advice["_avg_api_latency"] = self.total_api_latency / max(1, self.total_api_calls)
                return advice
            
            # Cache miss - start async fetch if not already pending
            self.cache_misses += 1
            if narrative not in self.pending_requests:
                self.pending_requests.add(narrative)
                thread = threading.Thread(target=self._fetch_advice_async, args=(narrative,))
                thread.daemon = True
                thread.start()
            
            # Return latest known advice immediately
            advice = self.latest_advice.copy()
            advice["_cache_hits"] = self.cache_hits
            advice["_cache_misses"] = self.cache_misses
            advice["_latest_api_latency"] = self.latest_api_latency
            advice["_avg_api_latency"] = self.total_api_latency / max(1, self.total_api_calls)
            return advice
