"""
LLM Coach interface and State-to-Text conversion for Google Research Football.

This module contains:
- GRFNarrator: Translates raw Simple115 observations into natural language descriptions.
- COACH_PROMPT_TEMPLATE: The template used to query the LLM Coach for roles and action masks.
"""

import math
import numpy as np


class GRFNarrator:
    """
    Translates raw Google Research Football (GRF) observations into descriptive
    natural language text, serving as the input state for the LLM Coach.

    Mathematical Logic for Coordinate-to-Text Translation:
    ------------------------------------------------------
    The GRF environment operates on a normalized 2D pitch coordinate system:
      - X-axis (length): Ranges from -1.0 (left goal) to +1.0 (right goal).
      - Y-axis (width): Ranges from -0.42 (top sideline) to +0.42 (bottom sideline).
      - Z-axis (height): Ranges from 0.0 to 1.0.

    Attacking Direction:
    By default, the active agent's team (Left Team) attacks the right goal, located at x = 1.0.
    The opponent (Right Team) attacks the left goal at x = -1.0.

    Spatial Zones (X-axis):
    We split the pitch into three zones to give the LLM high-level spatial context:
      - Defensive Third: x < -0.33
      - Midfield: -0.33 <= x <= 0.33
      - Attacking Third: x > 0.33

    Distance Calculations:
    Euclidean distance is calculated as sqrt((x2 - x1)^2 + (y2 - y1)^2).
    In GRF scale, a distance of 0.1 is roughly 5 meters. This allows us to quantify
    how "open" a teammate is or how close the ball is to the goal.
    """

    def __init__(self):
        pass

    def get_pitch_zone(self, x: float) -> str:
        """Returns the pitch zone based on the x-coordinate."""
        if x < -0.33:
            return "Defensive third"
        elif x <= 0.33:
            return "Midfield"
        else:
            return "Attacking third"

    def translate(self, features: dict) -> str:
        """
        Translates a parsed features dictionary into a concise narrative string.
        
        Args:
            features (dict): Dictionary generated by core.wrappers.observation_to_features()
            
        Returns:
            str: Natural language description of the game state.
        """
        ball_x = features.get("ball_x", 0.0)
        ball_y = features.get("ball_y", 0.0)
        active_idx = features.get("active_player_idx", -1)
        
        # Determine ball zone
        ball_zone = self.get_pitch_zone(ball_x)
        
        # Determine ball owner
        owner_id = features.get("ball_owned_team", -1)
        if owner_id == 0:
            owner_str = "Our team has the ball"
        elif owner_id == 1:
            owner_str = "The opposing team has the ball"
        else:
            owner_str = "The ball is loose"

        # Build basic narrative
        narrative = [
            f"Game State Summary:",
            f"- Ball Position: {ball_zone} (x={ball_x:.2f}, y={ball_y:.2f}).",
            f"- Possession: {owner_str}."
        ]

        if active_idx != -1:
            left_xs = features.get("left_team_xs", [])
            left_ys = features.get("left_team_ys", [])
            
            if active_idx < len(left_xs):
                ax, ay = left_xs[active_idx], left_ys[active_idx]
                narrative.append(f"- Active Agent (You): Player {active_idx} in {self.get_pitch_zone(ax)} (x={ax:.2f}, y={ay:.2f}).")
            
            # Add context for other teammates
            for i, (lx, ly) in enumerate(zip(left_xs, left_ys)):
                if i != active_idx:
                    dist = math.sqrt((lx - ball_x)**2 + (ly - ball_y)**2)
                    narrative.append(f"  * Teammate {i} is {dist:.2f} units away in {self.get_pitch_zone(lx)}.")

        return "\\n".join(narrative)


# Prompt template requesting the Role and Action Mask
COACH_PROMPT_TEMPLATE = """
You are an expert football coach analyzing a match in the Google Research Football environment.
The current game state is described below:

{narrative}

Your task is to:
1. Assign a tactical "Role" to the active agent (e.g., Attacker, Supporter, Defender).
2. Determine which of the 19 possible actions should be FORBIDDEN based on this role and the current state.

Available Actions in GRF (0-18):
0: Idle
1: Left, 2: TopLeft, 3: Top, 4: TopRight
5: Right, 6: BottomRight, 7: Bottom, 8: BottomLeft
9: LongPass, 10: HighPass, 11: ShortPass, 12: Shot
13: Sprint, 14: ReleaseDirection, 15: ReleaseSprint
16: Sliding, 17: Dribble, 18: ReleaseDribble

Output your response strictly in the following JSON format:
{{
    "Role": "<role_name>",
    "Forbidden_Actions": [<list of integer action IDs to mask>]
}}
"""

class MockDeepSeekCoach:
    """
    A predictable mock service for DeepSeek V3.2 to test the end-to-end pipeline
    before plugging in the real API.
    It evaluates the state locally to simulate consistent, coherent coaching behavior.
    """
    def __init__(self):
        pass

    def get_coaching_advice(self, features: dict) -> dict:
        """
        Takes the parsed features dict directly and returns structured JSON-like dict.
        """
        ball_owned_team = features.get("ball_owned_team", -1)
        ball_dist_to_goal = features.get("ball_dist_to_goal", 1.0)
        ball_x = features.get("ball_x", 0.0)
        
        forbidden_actions = []
        role = "Unknown"

        if ball_owned_team == 1:
            role = "Defender"
            # Forbid passing/shooting when defending
            forbidden_actions.extend([9, 10, 11, 12])  
        elif ball_owned_team == 0:
            if ball_dist_to_goal < 0.4:
                role = "Attacker (Shooting)"
                # Encourage shooting by forbidding passes near goal
                forbidden_actions.extend([9, 10, 11])  
            elif ball_x < -0.3:
                role = "Build-up (Defensive Half)"
                forbidden_actions.append(12)  # Forbid shooting from own half
            else:
                role = "Attacker (Midfield)"
                forbidden_actions.append(12)  # Forbid shooting from midfield
                
            # No sliding when owning ball
            forbidden_actions.append(16)  
        else:
            role = "Chaser"
            forbidden_actions.extend([9, 10, 11, 12])
            
        return {
            "Forbidden_Actions": list(set(forbidden_actions))
        }

class DeepSeekCoach:
    """
    Production service for DeepSeek V3.2 API integration.
    Queries the LLM with the game narrative to determine tactical roles and Action Masks.
    """
    def __init__(self, api_key: str, model: str = "deepseek-chat"):
        try:
            from openai import OpenAI
        except ImportError:
            raise ImportError("Please install the `openai` package to use the DeepSeek API.")
            
        self.narrator = GRFNarrator()
        self.client = OpenAI(
            api_key=api_key, 
            base_url="https://api.deepseek.com"
        )
        self.model = model
        self.total_tokens_used = 0

    def get_coaching_advice(self, features: dict) -> dict:
        """
        Translates the state into narrative, queries the DeepSeek API, and returns parsed JSON.
        """
        import json
        narrative = self.narrator.translate(features)
        prompt = COACH_PROMPT_TEMPLATE.format(narrative=narrative)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a tactical football coach. Respond strictly in JSON format."},
                    {"role": "user", "content": prompt}
                ],
                response_format={
                    'type': 'json_object'
                },
                max_tokens=100,
                temperature=0.0
            )
            
            raw_content = response.choices[0].message.content
            advice = json.loads(raw_content)
            
            # Track the tokens used
            if response.usage:
                self.total_tokens_used += response.usage.total_tokens
                
            # Basic validation
            if "Role" not in advice:
                 advice["Role"] = "Unknown"
            if "Forbidden_Actions" not in advice:
                 advice["Forbidden_Actions"] = []
                 
            # Append token metadata so the callback can monitor it
            advice["_tokens_used_this_call"] = response.usage.total_tokens if response.usage else 0
            advice["_total_tokens_used"] = self.total_tokens_used
                 
            return advice
            
        except Exception as e:
            print(f"[DeepSeekCoach] API Error: {e}. Falling back to empty mask.")
            return {
                "Role": "Fallback (Error)",
                "Forbidden_Actions": [],
                "_tokens_used_this_call": 0,
                "_total_tokens_used": getattr(self, "total_tokens_used", 0)
            }

class GroqCoach:
    """
    Production service for Groq API integration (e.g., Llama 3).
    Queries the LLM with the game narrative to determine tactical roles and Action Masks.
    """
    def __init__(self, api_key: str, model: str = "llama-3.1-8b-instant"):
        try:
            from groq import Groq
        except ImportError:
            raise ImportError("Please install the `groq` package to use the Groq API.")
            
        self.narrator = GRFNarrator()
        self.client = Groq(api_key=api_key)
        self.model = model
        self.total_tokens_used = 0

    def get_coaching_advice(self, features: dict) -> dict:
        """
        Translates the state into narrative, queries the Groq API, and returns parsed JSON.
        """
        import json
        narrative = self.narrator.translate(features)
        prompt = COACH_PROMPT_TEMPLATE.format(narrative=narrative)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a tactical football coach. Respond strictly in JSON format."},
                    {"role": "user", "content": prompt}
                ],
                response_format={
                    'type': 'json_object'
                },
                max_tokens=200,
                temperature=0.0
            )
            
            raw_content = response.choices[0].message.content
            advice = json.loads(raw_content)
            
            # Track the tokens used
            if response.usage:
                self.total_tokens_used += response.usage.total_tokens
                
            # Basic validation
            if "Role" not in advice:
                 advice["Role"] = "Unknown"
            if "Forbidden_Actions" not in advice:
                 advice["Forbidden_Actions"] = []
                 
            # Append token metadata so the callback can monitor it
            advice["_tokens_used_this_call"] = response.usage.total_tokens if response.usage else 0
            advice["_total_tokens_used"] = self.total_tokens_used
                 
            return advice
            
        except Exception as e:
            print(f"[GroqCoach] API Error: {e}. Falling back to empty mask.")
            return {
                "Role": "Fallback (Error)",
                "Forbidden_Actions": [],
                "_tokens_used_this_call": 0,
                "_total_tokens_used": getattr(self, "total_tokens_used", 0)
            }

